version: "3.8"

services:
  # MS SQL Server Database
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=${MSSQL_PID}
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - app-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          '/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${SA_PASSWORD} -Q ''SELECT 1 FROM Std_info_sys.sys.databases WHERE name = "Std_info_sys"''',
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s

  # ASP.NET Core Web API Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultDatabase=Server=${DB_SERVER},${DB_PORT};Database=${DATABASE_NAME};User Id=${DB_USER_ID};Password=${DB_USER_PASSWORD};TrustServerCertificate=true
      - JwtSettings__Key=${JWT_SECRET_KEY}
      - JwtSettings__Issuer=${JWT_ISSUER}
      - JwtSettings__Audience=${JWT_AUDIENCE}
      - JwtSettings__ExpiryMinutes=${JWT_EXPIRY_MINUTES}
      - AllowedOrigins__0=http://localhost
      - AllowedOrigins__1=http://localhost:80
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app-network

  # React Vite Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  sqldata:

networks:
  app-network:
    driver: bridge
